---
title: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Business and its neighbourhood – factors driving restaurants locations in Warsaw 

**The whole paper can be found under [this link](licencjat.pdf).**

This is a summary of my Bachelors Thesis paper at Faculty of Economics - University of Warsaw. Main goal was to assess, which factors are crucial in locations of restaurants in particular region of Warsaw. The paper is currently under review in *Statistics in Transition* Journal. 

#### Summary of the paper:

- Methods:
  - Machine Learning - Random Forest and Logistic Regression models
  - Explainable AI - Model Class Reliance for assesment of features relative importance, independent from the model tested
  - Spatial issues - Spatial dependency tests, spatial data wranglng, usage of Spatial Weights in the modeling
  - R caret package
  - Web scraping
  
- Factors driving restaurants location:
  - Presence of businesses in the area - most important factor
  - Proximity of other restaurants - still important factor
  - Population density in the area - not important
  - Communication infrastructure (bus stops, roads) - not important
  
  
  
  
  
  
  